import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-background to-muted">
      <div className="container mx-auto px-4 py-16">
        {/* Header */}
        <div className="text-center mb-16">
          <Badge variant="outline" className="mb-4">
            Generated by Etlaq Studio AI ✨
          </Badge>
          <h1 className="text-4xl font-bold tracking-tight lg:text-6xl mb-6">
            Welcome to your Etlaq app!
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
            This project was built using Etlaq Studio&apos;s AI-powered development platform.
            Ready to customize and scale.
          </p>
        </div>

        {/* Feature Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-16">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                🤖 AI-Generated
              </CardTitle>
              <CardDescription>
                Created using advanced AI with complete project structure
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                This application was built using Etlaq Studio&apos;s conversational AI system.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                🎨 Design System Ready
              </CardTitle>
              <CardDescription>
                Shadcn/ui components and Tailwind CSS included
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Beautiful, accessible components ready for customization.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                📚 Version Controlled
              </CardTitle>
              <CardDescription>
                Automatic GitHub integration and deployment
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                All changes are tracked and deployed automatically.
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Tech Stack */}
        <div className="text-center mb-12">
          <h2 className="text-2xl font-semibold mb-6">Built with Modern Tech Stack</h2>
          <div className="flex flex-wrap justify-center gap-2">
            <Badge variant="secondary">Next.js 15</Badge>
            <Badge variant="secondary">TypeScript</Badge>
            <Badge variant="secondary">Tailwind CSS</Badge>
            <Badge variant="secondary">Shadcn/ui</Badge>
            <Badge variant="secondary">ESLint</Badge>
            <Badge variant="secondary">App Router</Badge>
          </div>
        </div>

        {/* Call to Action */}
        <Alert className="max-w-2xl mx-auto">
          <AlertDescription className="text-center">
            🚀 Start building by chatting with AI to modify and enhance your application.
            <div className="mt-4">
              <Button className="mx-2">
                Start Building
              </Button>
              <Button variant="outline" className="mx-2">
                View Documentation
              </Button>
            </div>
          </AlertDescription>
        </Alert>

        {/* Footer */}
        <footer className="text-center mt-16 text-sm text-muted-foreground">
          <p>
            Powered by{" "}
            <a href="https://etlaq.studio" className="font-medium hover:underline">
              Etlaq Studio
            </a>
            {" "}• AI-Powered Development
          </p>
        </footer>
      </div>
    </main>
  );
}
